// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.26.1
// source: apply.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Command_Op int32

const (
	Command_PUT    Command_Op = 0
	Command_GET    Command_Op = 1
	Command_DELETE Command_Op = 2
)

// Enum value maps for Command_Op.
var (
	Command_Op_name = map[int32]string{
		0: "PUT",
		1: "GET",
		2: "DELETE",
	}
	Command_Op_value = map[string]int32{
		"PUT":    0,
		"GET":    1,
		"DELETE": 2,
	}
)

func (x Command_Op) Enum() *Command_Op {
	p := new(Command_Op)
	*p = x
	return p
}

func (x Command_Op) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Command_Op) Descriptor() protoreflect.EnumDescriptor {
	return file_apply_proto_enumTypes[0].Descriptor()
}

func (Command_Op) Type() protoreflect.EnumType {
	return &file_apply_proto_enumTypes[0]
}

func (x Command_Op) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Command_Op.Descriptor instead.
func (Command_Op) EnumDescriptor() ([]byte, []int) {
	return file_apply_proto_rawDescGZIP(), []int{0, 0}
}

type Command struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Op    Command_Op `protobuf:"varint,1,opt,name=op,proto3,enum=raftpb.Command_Op" json:"op,omitempty"`
	Key   string     `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value string     `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Command) Reset() {
	*x = Command{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apply_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_apply_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_apply_proto_rawDescGZIP(), []int{0}
}

func (x *Command) GetOp() Command_Op {
	if x != nil {
		return x.Op
	}
	return Command_PUT
}

func (x *Command) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Command) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ApplyArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command *Command `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
}

func (x *ApplyArgs) Reset() {
	*x = ApplyArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apply_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApplyArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyArgs) ProtoMessage() {}

func (x *ApplyArgs) ProtoReflect() protoreflect.Message {
	mi := &file_apply_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyArgs.ProtoReflect.Descriptor instead.
func (*ApplyArgs) Descriptor() ([]byte, []int) {
	return file_apply_proto_rawDescGZIP(), []int{1}
}

func (x *ApplyArgs) GetCommand() *Command {
	if x != nil {
		return x.Command
	}
	return nil
}

type ApplyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VirtualIndex int64 `protobuf:"varint,1,opt,name=virtual_index,json=virtualIndex,proto3" json:"virtual_index,omitempty"`
	Term         int32 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Success      bool  `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *ApplyReply) Reset() {
	*x = ApplyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apply_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApplyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyReply) ProtoMessage() {}

func (x *ApplyReply) ProtoReflect() protoreflect.Message {
	mi := &file_apply_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyReply.ProtoReflect.Descriptor instead.
func (*ApplyReply) Descriptor() ([]byte, []int) {
	return file_apply_proto_rawDescGZIP(), []int{2}
}

func (x *ApplyReply) GetVirtualIndex() int64 {
	if x != nil {
		return x.VirtualIndex
	}
	return 0
}

func (x *ApplyReply) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *ApplyReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_apply_proto protoreflect.FileDescriptor

var file_apply_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x61, 0x70, 0x70, 0x6c, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x72,
	0x61, 0x66, 0x74, 0x70, 0x62, 0x22, 0x79, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x12, 0x22, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x72,
	0x61, 0x66, 0x74, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x4f, 0x70,
	0x52, 0x02, 0x6f, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x22, 0x0a, 0x02,
	0x4f, 0x70, 0x12, 0x07, 0x0a, 0x03, 0x50, 0x55, 0x54, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x47,
	0x45, 0x54, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x02,
	0x22, 0x36, 0x0a, 0x09, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x41, 0x72, 0x67, 0x73, 0x12, 0x29, 0x0a,
	0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x72, 0x61, 0x66, 0x74, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52,
	0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0x5f, 0x0a, 0x0a, 0x41, 0x70, 0x70, 0x6c,
	0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x23, 0x0a, 0x0d, 0x76, 0x69, 0x72, 0x74, 0x75, 0x61,
	0x6c, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x76,
	0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x65, 0x72, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x65, 0x72, 0x6d, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32, 0x37, 0x0a, 0x05, 0x41, 0x70, 0x70,
	0x6c, 0x79, 0x12, 0x2e, 0x0a, 0x05, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x12, 0x11, 0x2e, 0x72, 0x61,
	0x66, 0x74, 0x70, 0x62, 0x2e, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x12,
	0x2e, 0x72, 0x61, 0x66, 0x74, 0x70, 0x62, 0x2e, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x42, 0x1f, 0x5a, 0x1d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x72, 0x61, 0x66, 0x74, 0x2d, 0x6b, 0x76, 0x2f, 0x72, 0x61, 0x66, 0x74, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_apply_proto_rawDescOnce sync.Once
	file_apply_proto_rawDescData = file_apply_proto_rawDesc
)

func file_apply_proto_rawDescGZIP() []byte {
	file_apply_proto_rawDescOnce.Do(func() {
		file_apply_proto_rawDescData = protoimpl.X.CompressGZIP(file_apply_proto_rawDescData)
	})
	return file_apply_proto_rawDescData
}

var file_apply_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_apply_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_apply_proto_goTypes = []interface{}{
	(Command_Op)(0),    // 0: raftpb.Command.Op
	(*Command)(nil),    // 1: raftpb.Command
	(*ApplyArgs)(nil),  // 2: raftpb.ApplyArgs
	(*ApplyReply)(nil), // 3: raftpb.ApplyReply
}
var file_apply_proto_depIdxs = []int32{
	0, // 0: raftpb.Command.op:type_name -> raftpb.Command.Op
	1, // 1: raftpb.ApplyArgs.command:type_name -> raftpb.Command
	2, // 2: raftpb.Apply.Apply:input_type -> raftpb.ApplyArgs
	3, // 3: raftpb.Apply.Apply:output_type -> raftpb.ApplyReply
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_apply_proto_init() }
func file_apply_proto_init() {
	if File_apply_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apply_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apply_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApplyArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apply_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApplyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apply_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apply_proto_goTypes,
		DependencyIndexes: file_apply_proto_depIdxs,
		EnumInfos:         file_apply_proto_enumTypes,
		MessageInfos:      file_apply_proto_msgTypes,
	}.Build()
	File_apply_proto = out.File
	file_apply_proto_rawDesc = nil
	file_apply_proto_goTypes = nil
	file_apply_proto_depIdxs = nil
}
